FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

ADD . /app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/api-main.go

FROM alpine:latest AS production

ENV PORT=2020
ENV GIN_MODE=release

COPY --from=builder /app/main .

CMD ["./main"]