version: '3'
services:
  redis:
    image: redis:latest

  verve-storage-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "2020:2020"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379

  verve-storage-file-parser:
    build:
      context: .
      dockerfile: Dockerfile.file-parser
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
